name: SLSA Go releaser
on:
  workflow_dispatch:
  release:
    types: [created]
  push:
    branches:
      - master

permissions: read-all
jobs:

  build:
    permissions:
      id-token: write # To sign the provenance.
      contents: write # To upload assets to release.
      actions: read # To read the workflow path.
    strategy:
      matrix:
        os:
        - linux
        arch:
        - amd64
        - arm64
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.1.0
    with:
      go-version: 1.24
      config-file: .slsa-goreleaser/${{matrix.os}}-${{matrix.arch}}.yml
